- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: testserver
  become: true
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
 
    - name: restart-apache
      service:
        name: apache2
        state: started
